baseurl: "/"
languageCode: "en-us"
title: "sgee R"
theme: "tania"
paginate: 6
googleAnalytics: UA-164754969-1

params:
  titleEmoji: '😎'
  socialOptions:
    github: https://github.com/Scott-Gee
    linkedin: https://www.linkedin.com/in/scott-gee-1aa262144/
  enableFootnotes: false
  subtitle: Personal blog with R tips

menu:
  header:
    - name: About
      url: "/about/"
    - name: Posts
      url: "/articles/"
    - name: Preppin' Data
      url: "/2021/06/08/preppin-data-index/"
    - name: Tags
      url: "/tags/"  


markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true